In [2]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd

# transfering datasets to phpmyadmin

In [3]:
# fill with your id and password
USERNAME =
PASSWORD =
HOST = '127.0.0.1'
PORT = '3306'
DATABASE = 'recommandation'

In [4]:
# get connexion to database
connection = pymysql.connect(host='localhost', 
                             user=USERNAME, 
                             password=PASSWORD, 
                             db=DATABASE)

cursor = connection.cursor()

In [4]:
DB_URL = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOST, PORT, DATABASE)

engine = create_engine(DB_URL)

In [8]:
# load csv
tags = pd.read_csv('data/tags.csv')
# add tags csv to database
tags.to_sql('tags', con=engine, if_exists='append', chunksize=1000)

In [9]:
# load csv
books = pd.read_csv('data/books.csv')
# add books csv to database
books.to_sql('books', con=engine, if_exists='append', chunksize=1000)

In [5]:
# load csv
books_with_cat = pd.read_csv('data/books_with_cat.csv')
# add books with tags csv to database
books_with_cat.to_sql('books_with_cat', con=engine, if_exists='append', chunksize=1000)

In [11]:
# load csv
ratings = pd.read_csv('data/ratings.csv')
# add ratings csv to database
ratings.to_sql('ratings', con=engine, if_exists='append', chunksize=1000)

In [37]:
ratings.describe()

            user_id       book_id        rating
count  5.976479e+06  5.976479e+06  5.976479e+06
mean   2.622446e+04  2.006477e+03  3.919866e+00
std    1.541323e+04  2.468499e+03  9.910868e-01
min    1.000000e+00  1.000000e+00  1.000000e+00
25%    1.281300e+04  1.980000e+02  3.000000e+00
50%    2.593800e+04  8.850000e+02  4.000000e+00
75%    3.950900e+04  2.973000e+03  5.000000e+00
max    5.342400e+04  1.000000e+04  5.000000e+00

In [10]:
# load csv
book_tags = pd.read_csv('data/book_tags.csv')
# add books tags csv to database
book_tags.to_sql('book_tags', con=engine, if_exists='append', chunksize=1000)

In [5]:
# load csv
to_read = pd.read_csv('data/to_read.csv')
# add to read csv to database
to_read.to_sql('to_read', con=engine, if_exists='append', chunksize=1000)

In [8]:
to_read.describe()

             user_id        book_id
count  912705.000000  912705.000000
mean    27668.980115    2454.739538
std     14775.096388    2626.359921
min         1.000000       1.000000
25%     15507.000000     360.000000
50%     27799.000000    1381.000000
75%     40220.000000    3843.000000
max     53424.000000   10000.000000

In [6]:
cursor.execute('SELECT * FROM recommandation.books')

10000

In [7]:
books_with_cat = pd.read_sql_query('SELECT * FROM recommandation.books_with_cat',connection, index_col = 'index')
books_with_cat

,Unnamed: 0,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,...,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,category
index,,,,,,,,,,,,,,,,,,,,,
0,0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,...,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,action & adventure
1,1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,...,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,fantasy
2,2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,...,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,fantasy
3,3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,...,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,classic
4,4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,...,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,classic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,9996,7130616,7130616,7392860,19,441019455,9.780441e+12,Ilona Andrews,2010.0,...,18856,1180,105,575,3538,7860,6778,https://images.gr-assets.com/books/1307445460m...,https://images.gr-assets.com/books/1307445460s...,fantasy
9996,9996,9997,208324,208324,1084709,19,067973371X,9.780680e+12,Robert A. Caro,1990.0,...,12952,395,303,551,1737,3389,6972,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...,memoir & autobiography
9997,9997,9998,77431,77431,2393986,60,039330762X,9.780393e+12,Patrick O'Brian,1977.0,...,10733,374,11,111,1191,4240,5180,https://images.gr-assets.com/books/1455373531m...,https://images.gr-assets.com/books/1455373531s...,historical fiction
9998,9998,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,...,11994,1988,275,1002,3765,4577,2375,https://images.gr-assets.com/books/1279214118m...,https://images.gr-assets.com/books/1279214118s...,memoir & autobiography
9999,9999,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,...,9700,364,117,345,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...,history

In [7]:
books = pd.read_sql_query('SELECT * FROM recommandation.books',connection, index_col = 'index')
books

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
index,,,,,,,,,,,,,,,,,,,,,
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,7130616,7130616,7392860,19,441019455,9.780441e+12,Ilona Andrews,2010.0,Bayou Moon,...,17204,18856,1180,105,575,3538,7860,6778,https://images.gr-assets.com/books/1307445460m...,https://images.gr-assets.com/books/1307445460s...
9996,9997,208324,208324,1084709,19,067973371X,9.780680e+12,Robert A. Caro,1990.0,Means of Ascent,...,12582,12952,395,303,551,1737,3389,6972,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...
9997,9998,77431,77431,2393986,60,039330762X,9.780393e+12,Patrick O'Brian,1977.0,The Mauritius Command,...,9421,10733,374,11,111,1191,4240,5180,https://images.gr-assets.com/books/1455373531m...,https://images.gr-assets.com/books/1455373531s...
9998,9999,8565083,8565083,13433613,7,61711527,9.780062e+12,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,...,11279,11994,1988,275,1002,3765,4577,2375,https://images.gr-assets.com/books/1279214118m...,https://images.gr-assets.com/books/1279214118s...
9999,10000,8914,8914,11817,31,375700455,9.780376e+12,John Keegan,1998.0,The First World War,...,9162,9700,364,117,345,2031,4138,3069,https://images.gr-assets.com/books/1403194704m...,https://images.gr-assets.com/books/1403194704s...

In [14]:
categories = ['action & adventure', 'fantasy', 'romance', 'mystery & thriller', 'classic',
              'memoir & autobiography', 'historical fiction', 'graphic novel & comic',
              'science fiction', 'history', 'horror', "children's", 'science', 'humor',
              'self development', 'dystopia', 'paranormal romance', 'anthology', 'poetry',
              'cookbooks', 'essay', 'drama', 'other']


print(categories[0:5])
print(categories[5:10])
print(categories[10:15])
print(categories[15:20])
print(categories[20:])

['action & adventure', 'fantasy', 'romance', 'mystery & thriller', 'classic']
['memoir & autobiography', 'historical fiction', 'graphic novel & comic', 'science fiction', 'history']
['horror', "children's", 'science', 'humor', 'self development']
['dystopia', 'paranormal romance', 'anthology', 'poetry', 'cookbooks']
['essay', 'drama', 'other']

In [32]:
categories2 = ['action & adventure', 'fantasy', 'romance', 'mystery & thriller', 'classic']
remain = 0
if len(categories2)%5 != 0:
    remain = 1

for i in range(0,len(categories2)//5 + remain):
    start = i*5
    end = start + 5
    print(categories2[start:end])

['action & adventure', 'fantasy', 'romance', 'mystery & thriller', 'classic']